services:
  waf:
    volumes:
      - ./waf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./waf/conf.d-pass-through:/etc/nginx/conf.d:ro
      - ./waf/certs:/etc/nginx/certs:ro
      - ./logs/waf:/var/log/nginx
